spring:
  application:
    name: barber-shop-api
  datasource: 
    url: jdbc:postgresql://localhost:5432/barber_shop
    username: minion
    password: 1234
  jpa:
    hibernate:
      ddl-auto: validate
